# Generated by Django 6.0.3 on 2026-03-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelTable(
            name='slide',
            table='shop_slides',
        ),
    ]
