# Generated by Django 6.0.3 on 2026-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterModelTable(
            name='slide',
            table=None,
        ),
    ]
